version: '3'

services:
  pgdb-tests:
    image: postgres:14
    environment:
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
      - POSTGRES_SERVER=pgdb-tests
    env_file:
      - .env
    restart: always

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=pgdb-tests
    command: bash -c "./docker.tests.sh"
    depends_on:
      - pgdb-tests
