version: '3'

services:
  db:
    image: mariadb:10.7
    env_file:
      - .env
    restart: always
    volumes:
      - ./db:/var/lib/mysql

  pgdb:
    image: postgres:14
    environment:
      - POSTGRES_INITDB_ARGS='--encoding=UTF-8'
    env_file:
      - .env
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    command: bash -c "./docker.start.sh"
    depends_on:
      - db
      - pgdb
    volumes:
      - ./log:/src/log

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_DOMAIN: ${VUE_APP_DOMAIN}
        VUE_APP_DEMOMODE: ${VUE_APP_DEMOMODE}
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - backend
