"""0.2.04 Use Folder for JSONDoc and Markdown access control

Revision ID: 5d93a91d55d2
Revises: 3300d0b4f65f
Create Date: 2022-09-19 18:04:16.553463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d93a91d55d2'
down_revision = '3300d0b4f65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jsondoc_user', table_name='jsondoc')
    op.drop_constraint('jsondoc_user_fkey', 'jsondoc', type_='foreignkey')
    op.drop_column('jsondoc', 'user')
    op.drop_index('ix_markdown_user', table_name='markdown')
    op.drop_constraint('markdown_user_fkey', 'markdown', type_='foreignkey')
    op.drop_column('markdown', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markdown', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('markdown_user_fkey', 'markdown', 'user', ['user'], ['uid'], ondelete='CASCADE')
    op.create_index('ix_markdown_user', 'markdown', ['user'], unique=False)
    op.add_column('jsondoc', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('jsondoc_user_fkey', 'jsondoc', 'user', ['user'], ['uid'], ondelete='CASCADE')
    op.create_index('ix_jsondoc_user', 'jsondoc', ['user'], unique=False)
    # ### end Alembic commands ###
