"""0.1.1 Added user creation timestamp

Revision ID: 18e77acb34af
Revises: e8d94c93e199
Create Date: 2022-04-25 12:08:23.464058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e77acb34af'
down_revision = 'e8d94c93e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_dt', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_dt')
    # ### end Alembic commands ###
