"""0.1.4 FIX MemorizeCard ondelete

Revision ID: 4ceee46ca515
Revises: ff5f2a77f739
Create Date: 2022-05-18 22:01:30.039008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ceee46ca515'
down_revision = 'ff5f2a77f739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('memorizecard_ibfk_1', 'memorizecard', type_='foreignkey')
    op.create_foreign_key(None, 'memorizecard', 'memorizecategory', ['category'], ['uid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memorizecard', type_='foreignkey')
    op.create_foreign_key('memorizecard_ibfk_1', 'memorizecard', 'memorizecategory', ['category'], ['uid'])
    # ### end Alembic commands ###
