"""0.1 Initial version

Revision ID: e8d94c93e199
Revises: 
Create Date: 2022-04-04 18:45:29.530051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d94c93e199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daystate',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('statedate', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('complited', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('user', 'statedate')
    )
    op.create_index(op.f('ix_daystate_statedate'), 'daystate', ['statedate'], unique=False)
    op.create_index(op.f('ix_daystate_user'), 'daystate', ['user'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('coreactivity', sa.Integer(), nullable=True),
    sa.Column('coretasklist', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=False)
    op.create_table('dailytask',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_dailytask_uid'), 'dailytask', ['uid'], unique=False)
    op.create_index(op.f('ix_dailytask_user'), 'dailytask', ['user'], unique=False)
    op.create_table('jsondoc',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('doctype', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('jsondoc', mysql.MEDIUMTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_jsondoc_uid'), 'jsondoc', ['uid'], unique=False)
    op.create_index(op.f('ix_jsondoc_user'), 'jsondoc', ['user'], unique=False)
    op.create_table('markdown',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('md', mysql.MEDIUMTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_markdown_uid'), 'markdown', ['uid'], unique=False)
    op.create_index(op.f('ix_markdown_user'), 'markdown', ['user'], unique=False)
    op.create_table('regulartask',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('nextdate', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_regulartask_uid'), 'regulartask', ['uid'], unique=False)
    op.create_index(op.f('ix_regulartask_user'), 'regulartask', ['user'], unique=False)
    op.create_table('dailytaskstate',
    sa.Column('statedate', sa.Date(), nullable=False),
    sa.Column('dailytask', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dailytask'], ['dailytask.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statedate', 'dailytask')
    )
    op.create_index(op.f('ix_dailytaskstate_dailytask'), 'dailytaskstate', ['dailytask'], unique=False)
    op.create_index(op.f('ix_dailytaskstate_statedate'), 'dailytaskstate', ['statedate'], unique=False)
    op.create_table('regulartaskstate',
    sa.Column('statedate', sa.Date(), nullable=False),
    sa.Column('regulartask', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regulartask'], ['regulartask.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statedate', 'regulartask')
    )
    op.create_index(op.f('ix_regulartaskstate_regulartask'), 'regulartaskstate', ['regulartask'], unique=False)
    op.create_index(op.f('ix_regulartaskstate_statedate'), 'regulartaskstate', ['statedate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulartaskstate_statedate'), table_name='regulartaskstate')
    op.drop_index(op.f('ix_regulartaskstate_regulartask'), table_name='regulartaskstate')
    op.drop_table('regulartaskstate')
    op.drop_index(op.f('ix_dailytaskstate_statedate'), table_name='dailytaskstate')
    op.drop_index(op.f('ix_dailytaskstate_dailytask'), table_name='dailytaskstate')
    op.drop_table('dailytaskstate')
    op.drop_index(op.f('ix_regulartask_user'), table_name='regulartask')
    op.drop_index(op.f('ix_regulartask_uid'), table_name='regulartask')
    op.drop_table('regulartask')
    op.drop_index(op.f('ix_markdown_user'), table_name='markdown')
    op.drop_index(op.f('ix_markdown_uid'), table_name='markdown')
    op.drop_table('markdown')
    op.drop_index(op.f('ix_jsondoc_user'), table_name='jsondoc')
    op.drop_index(op.f('ix_jsondoc_uid'), table_name='jsondoc')
    op.drop_table('jsondoc')
    op.drop_index(op.f('ix_dailytask_user'), table_name='dailytask')
    op.drop_index(op.f('ix_dailytask_uid'), table_name='dailytask')
    op.drop_table('dailytask')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_daystate_user'), table_name='daystate')
    op.drop_index(op.f('ix_daystate_statedate'), table_name='daystate')
    op.drop_table('daystate')
    # ### end Alembic commands ###
