"""0.1.3 Memorize Card

Revision ID: ff5f2a77f739
Revises: c9c1f795957b
Create Date: 2022-05-12 00:08:10.911155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5f2a77f739'
down_revision = 'c9c1f795957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memorizecategory',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_memorizecategory_uid'), 'memorizecategory', ['uid'], unique=False)
    op.create_index(op.f('ix_memorizecategory_user'), 'memorizecategory', ['user'], unique=False)
    op.create_table('memorizestack',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_memorizestack_uid'), 'memorizestack', ['uid'], unique=False)
    op.create_index(op.f('ix_memorizestack_user'), 'memorizestack', ['user'], unique=False)
    op.create_table('memorizecard',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('stack', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('obverse', sa.String(length=1024), nullable=False),
    sa.Column('reverse', sa.String(length=4096), nullable=False),
    sa.Column('hint', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['memorizecategory.uid'], ),
    sa.ForeignKeyConstraint(['stack'], ['memorizestack.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_memorizecard_category'), 'memorizecard', ['category'], unique=False)
    op.create_index(op.f('ix_memorizecard_stack'), 'memorizecard', ['stack'], unique=False)
    op.create_index(op.f('ix_memorizecard_uid'), 'memorizecard', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memorizecard_uid'), table_name='memorizecard')
    op.drop_index(op.f('ix_memorizecard_stack'), table_name='memorizecard')
    op.drop_index(op.f('ix_memorizecard_category'), table_name='memorizecard')
    op.drop_table('memorizecard')
    op.drop_index(op.f('ix_memorizestack_user'), table_name='memorizestack')
    op.drop_index(op.f('ix_memorizestack_uid'), table_name='memorizestack')
    op.drop_table('memorizestack')
    op.drop_index(op.f('ix_memorizecategory_user'), table_name='memorizecategory')
    op.drop_index(op.f('ix_memorizecategory_uid'), table_name='memorizecategory')
    op.drop_table('memorizecategory')
    # ### end Alembic commands ###
