name: Tests and Build
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml up --abort-on-container-exit --exit-code-from backend

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          VUE_APP_DEMOMODE=0 VUE_APP_DOMAIN="" npm run build
          zip frontend.zip ./dist/* -r
          VUE_APP_DEMOMODE=1 VUE_APP_DOMAIN="" npm run build
          zip frontend_demo.zip ./dist/* -r
          echo $NOW > ./build_date

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: divetoh.ru
          username: deploy
          port: 22
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "frontend/frontend.zip,frontend/frontend_demo.zip,frontend/build_date"
          target: "deploy"

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: |
            frontend/frontend.zip
            frontend/frontend_demo.zip
            frontend/build_date
